# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('repetition', models.CharField(max_length=20, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('cog', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('vectorized', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('geometry_simple', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('geometry_medium', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('geometry_detail', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('cog', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('vectorized', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('geometry_simple', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('geometry_medium', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('geometry_detail', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geocode_api.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('cog', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('vectorized', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('geometry_simple', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('geometry_medium', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('geometry_detail', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('capital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reg_cap_id', to='geocode_api.Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('vectorized', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geocode_api.Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('municipalities', models.ManyToManyField(to='geocode_api.Municipality')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='capital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dep_cap_id', to='geocode_api.Municipality'),
        ),
        migrations.AddField(
            model_name='department',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geocode_api.Region'),
        ),
        migrations.AddField(
            model_name='address',
            name='way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geocode_api.Way'),
        ),
    ]
