# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocode_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'municipality', 'verbose_name_plural': 'municipalities'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'region', 'verbose_name_plural': 'regions'},
        ),
        migrations.AlterModelOptions(
            name='way',
            options={'verbose_name': 'way', 'verbose_name_plural': 'ways'},
        ),
        migrations.AlterModelOptions(
            name='zipcode',
            options={'verbose_name': 'zipcode', 'verbose_name_plural': 'zipcodes'},
        ),
    ]
